#!/bin/bash

# Define colors
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color


if [[ $# != 1 ]]; then
	echo ""
	echo -e "${RED}Incorrect number of command line arguments $# ${NC}"
	echo "Usage: $0 disk_device"
	echo "Ex   : $0 /dev/sdb"
	exit
fi


disk=$1
echo "Using disk     :" ${disk}
shortdisk=${disk:5}
echo "Short disk name:" ${shortdisk}

fstabfilename="/tmp/testfstab"
echo "Creating test fstab in /tmp called ${fstabfilename}"

uuidboot=`blkid /dev/${shortdisk}1 | sed -n "/${shortdisk}1/s/.* UUID=\"\([^\"]*\)\".*/\1/p"`
uuidroot=`blkid /dev/${shortdisk}2 | sed -n "/${shortdisk}2/s/.* UUID=\"\([^\"]*\)\".*/\1/p"`
uuidswap=`blkid /dev/${shortdisk}3 | sed -n "/${shortdisk}3/s/.* UUID=\"\([^\"]*\)\".*/\1/p"`

echo "#" 																		 > ${fstabfilename}
echo "# This file was automatically generated by $0" 							>> ${fstabfilename}
echo "# <file system> <mount point>   <type>  <options>       <dump>  <pass>" 	>> ${fstabfilename}
echo "#" 																		>> ${fstabfilename}
echo "UUID=${uuidboot} /boot/efi auto defaults 0 0" 							>> ${fstabfilename}
echo "UUID=${uuidroot} /               ext4    errors=remount-ro 0       1" 	>> ${fstabfilename}
echo "UUID=${uuidswap} none            swap    sw              0       0" 		>> ${fstabfilename}

cat ${fstabfilename}
